// <auto-generated />
namespace ASW.Shared.Requests.RemoteDriver
{
    public class UpdateRemoteDriverRequest
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string RegistrationNumber { get; set; } = string.Empty;
        public bool IsRemoved { get; set; } = false;
    }
}
