// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteAxesVel.Entities;

public class RemoteAxesVelEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid AxesVelId { get; set; }
    public Guid WeighingId { get; set; } = Guid.Empty;
    public int Number { get; set; }
    public double Tara { get; set; } = 0;
    public double Brutto { get; set; } = 0;
    public bool IsRemoved { get; set; }
}
