// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteUser.Entities;
public class RemoteUserEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid UsersId { get; set; }
    public string Login { get; set; } = string.Empty;
    public string Role { get; set; } = string.Empty;
    public string FullFIO { get; set; } = string.Empty;
    public string ReductionFIO { get; set; } = string.Empty;
    public Guid ModifiedId { get; set; } = Guid.Empty;
    public bool IsRemoved { get; set; }
}
