// <auto-generated />
namespace ASW.Shared.Requests.RemotePostUsers
{
    public class AddRemotePostUsersRequest
    {
        public Guid Id { get; set; }
        public Guid PostId { get; set; } = Guid.Empty;
        public string PostName { get; set; } = string.Empty;
        public Guid UserId { get; set; } = Guid.Empty;
        public string UserName { get; set; } = string.Empty;
    }
}
