// <auto-generated />
namespace ASW.Shared.Requests.Users
{
    public class UpdateUsersRequest
    {
        public Guid Id { get; set; }
        public string Login { get; set; } = string.Empty;
        public string Role { get; set; } = string.Empty;
        public string FullFIO { get; set; } = string.Empty;
        public string ReductionFIO { get; set; } = string.Empty;
        public Guid ModifiedId { get; set; } = Guid.Empty;
        public bool IsRemoved { get; set; } = false;
    }
}
