// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteGood.Entities;

public class RemoteGoodEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid GoodId { get; set; }
    public int Number { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Unit { get; set; } = string.Empty;
    public string VendorCode { get; set; } = string.Empty;
    public bool IsRemoved { get; set; }
}
