// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteCar.Entities;

public class RemoteCarEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid CarId { get; set; }
    public string GovernmentNumber { get; set; } = string.Empty;
    public string Brand { get; set; } = string.Empty;
    public string Model { get; set; } = string.Empty;
    public string Type { get; set; } = string.Empty;
    public Guid? DriverId { get; set; } = Guid.Empty;
    public string? DriverName { get; set; } = string.Empty;
    public Guid? GoodsId { get; set; } = Guid.Empty;
    public string? GoodsName { get; set; } = string.Empty;
    public Guid? TrailerId { get; set; } = Guid.Empty;
    public string? TrailerName { get; set; } = string.Empty;
    public Guid? SenderId { get; set; } = Guid.Empty;
    public string? SenderName { get; set; } = string.Empty;
    public Guid? RecipientId { get; set; } = Guid.Empty;
    public string? RecipientName { get; set; } = string.Empty;
    public Guid? CarrierId { get; set; } = Guid.Empty;
    public string? CarrierName { get; set; } = string.Empty;
    public Guid? PayerId { get; set; } = Guid.Empty;
    public string? PayerName { get; set; } = string.Empty;
    public string RFID { get; set; } = string.Empty;
    public bool IsRemoved { get; set; }
}
