// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemotePostUsers.Entities;
public class RemotePostUserEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid PostUsersId { get; set; }
    public Guid PostId { get; set; } = Guid.Empty;
    public string PostName { get; set; } = string.Empty;
    public Guid UserId { get; set; } = Guid.Empty;
    public string UserName { get; set; } = string.Empty;
    public bool IsRemoved {  get; set; }
}
