// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteActionLog.Entities;

public class RemoteActionLogEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid ActionLogId { get; set; }
    public DateTime? Date { get; set; }
    public Guid? UserId { get; set; } = Guid.Empty;
    public string UserName { get; set; } = string.Empty;
    public string WhereName { get; set; } = string.Empty;
    public int WhereId { get; set; }
    public string WhatName { get; set; } = string.Empty;
    public string WhatContent { get; set; } = string.Empty;
    public Guid WhatId { get; set; } = Guid.Empty;
    public string Was { get; set; } = string.Empty;
    public string Become { get; set; } = string.Empty;
    public bool IsRemoved { get; set; }
}
