// <auto-generated />
namespace ASW.Shared.Requests.RemoteWeighingAdditionalField
{
    public class UpdateRemoteWeighingAdditionalFieldRequest
    {
        public Guid Id { get; set; }
        public Guid AdditionalFieldId { get; set; } = Guid.Empty;
        public Guid WeighingId { get; set; } = Guid.Empty;
        public string Name { get; set; } = string.Empty;
        public bool IsSavedLastValue { get; set; } = false;
        public string Value { get; set; } = string.Empty;
        public bool IsRemoved { get; set; } = false;
    }
}
