// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteEmptyWeighing.Entities
{
    public class RemoteEmptyWeighingEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
    {
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid PlaceId { get; set; }
        public string PlaceName { get; set; } = string.Empty;
        public Guid EmptyWeighingId { get; set; }
        public Guid PostId { get; set; } = Guid.Empty;
        public string? PostName { get; set; } = string.Empty;
        public string? CarName { get; set; } = string.Empty;
        public string? TrailerName { get; set; } = string.Empty;
        public DateTime? Date { get; set; }
        public double Weight { get; set; } = 0;
        public bool Stability { get; set; }
        public bool IsRemoved { get; set; }
    }
}
