// <auto-generated />
namespace ASW.Shared.Requests.RemotePost
{
    public class AddRemotePostRequest
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public bool IsAutomaticMode { get; set; } = false;
        public string OperatingMode { get; set; } = string.Empty;
        public bool IsAutomaticDeviceModeOff { get; set; } = false;
        public bool IsRegisteringEmptyPassage { get; set; } = false;
        public double ThresholdBeginningWeighing { get; set; } = 0;
        public int DelayEmptyScales { get; set; }
        public int TerminalNumber { get; set; }
        public bool IsTcp { get; set; } = false;
        public string TCPIP { get; set; } = string.Empty;
        public int TCPPort { get; set; }
        public string ComName { get; set; } = string.Empty;
        public int ComSpeed { get; set; }
        public bool IsWeighingByAxes { get; set; } = false;
        public bool IsOnlyAxes { get; set; } = false;
        public string ServerIP { get; set; } = string.Empty;
        public int ServerPort { get; set; }
        public string ClientIP { get; set; } = string.Empty;
        public int ClientPort { get; set; }
        public bool IsRemoved { get; set; } = false;
    }
}
