// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemotePhotos.Entities;

public class RemoteEmptyWeighingPhotoEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid EmptyWeighingPhotoId { get; set; }
    public Guid EmptyWeighingId { get; set; } = Guid.Empty;
    public DateTime? Date { get; set; }
    public string Base64Image { get; set; } = string.Empty;
    public bool IsRemoved { get; set; }
}
