// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteWeighingAdditionalField.Entities;

public class RemoteWeighingAdditionalFieldEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid WeighingAdditionalFieldId { get; set; }
    public Guid AdditionalFieldId { get; set; } = Guid.Empty;
    public Guid WeighingId { get; set; } = Guid.Empty;
    public string Name { get; set; } = string.Empty;
    public bool IsSavedLastValue { get; set; }
    public string Value { get; set; } = string.Empty;
    public bool IsRemoved { get; set; }
}
