// <auto-generated />
namespace ASW.Shared.Requests.RemoteAdditionalField
{
    public class UpdateRemoteAdditionalFieldRequest
    {
        public Guid Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public bool IsSavedLastValue { get; set; } = false;
        public string DefaultValue { get; set; } = string.Empty;
        public bool IsRemoved { get; set; } = false;
    }
}
