// <auto-generated />
namespace ASW.Shared.Requests.RemoteActionLog
{
    public class AddRemoteActionLogRequest
    {
        public Guid Id { get; set; }
        public DateTime? Date { get; set; }
        public Guid? UserId { get; set; } = Guid.Empty;
        public string UserName { get; set; } = string.Empty;
        public string WhereName { get; set; } = string.Empty;
        public int WhereId { get; set; }
        public string WhatName { get; set; } = string.Empty;
        public string WhatContent { get; set; } = string.Empty;
        public Guid WhatId { get; set; } = Guid.Empty;
        public string Was { get; set; } = string.Empty;
        public string Become { get; set; } = string.Empty;
        public bool IsRemoved { get; set; } = false;
    }
}
