// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteCounterparty.Entities;
public class RemoteCounterpartyEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid CounterpartyId { get; set; }
    public string Name { get; set; } = string.Empty;
    public string LegalAddress { get; set; } = string.Empty;
    public string ActualAddress { get; set; } = string.Empty;
    public string Contacts { get; set; } = string.Empty;
    public string INN { get; set; } = string.Empty;
    public string KPP { get; set; } = string.Empty;
    public string OGRN { get; set; } = string.Empty;
    public bool IsWarehouse { get; set; }
    public bool IsRemoved { get; set; }
}
