// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteWarehouseMovement.Entities;

public class RemoteWarehouseMovementsEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid PlaceId { get; set; }
    public string PlaceName { get; set; } = string.Empty;
    public Guid WarehouseMovementsId { get; set; }
    public Guid WeighingId { get; set; } = Guid.Empty;
    public Guid PostId { get; set; } = Guid.Empty;
    public string PostName { get; set; } = string.Empty;
    public Guid CounterpartyId { get; set; } = Guid.Empty;
    public Guid? AddedUserId { get; set; } = Guid.Empty;
    public string? AddedUserName { get; set; } = string.Empty;
    public DateTime? DateCreation { get; set; }
    public Guid? GoodsId { get; set; } = Guid.Empty;
    public string? GoodsName { get; set; } = string.Empty;
    public double Netto { get; set; } = 0;
    public bool IsManualInput { get; set; }
    public bool IsRemoved { get; set; }
}
