// <auto-generated />
namespace ASW.Shared.Requests.RemotePhotoBrutto
{
    public class AddRemotePhotoBruttoRequest
    {
        public Guid Id { get; set; }
        public Guid WeighingId { get; set; } = Guid.Empty;
        public DateTime? Date { get; set; }
        public string Base64Image { get; set; } = string.Empty;
    }
}
