// <auto-generated />
namespace ASW.Shared.Requests.RemoteCar
{
    public class UpdateRemoteCarRequest
    {
        public Guid Id { get; set; }
        public string GovernmentNumber { get; set; } = string.Empty;
        public string Brand { get; set; } = string.Empty;
        public string Model { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
        public Guid? DriverId { get; set; } = Guid.Empty;
        public string? DriverName { get; set; } = string.Empty;
        public Guid? GoodsId { get; set; } = Guid.Empty;
        public string? GoodsName { get; set; } = string.Empty;
        public Guid? TrailerId { get; set; } = Guid.Empty;
        public string? TrailerName { get; set; } = string.Empty;
        public Guid? SenderId { get; set; } = Guid.Empty;
        public string? SenderName { get; set; } = string.Empty;
        public Guid? RecipientId { get; set; } = Guid.Empty;
        public string? RecipientName { get; set; } = string.Empty;
        public Guid? CarrierId { get; set; } = Guid.Empty;
        public string? CarrierName { get; set; } = string.Empty;
        public Guid? PayerId { get; set; } = Guid.Empty;
        public string? PayerName { get; set; } = string.Empty;
        public string RFID { get; set; } = string.Empty;
        public bool IsRemoved { get; set; } = false;
    }
}
