// <auto-generated />
namespace ASW.Shared.Requests.RemoteWarehouseMovements
{
    public class UpdateRemoteWarehouseMovementsRequest
    {
        public Guid Id { get; set; }
        public Guid WeighingId { get; set; } = Guid.Empty;
        public Guid PostId { get; set; } = Guid.Empty;
        public string PostName { get; set; } = string.Empty;
        public Guid CounterpartyId { get; set; } = Guid.Empty;
        public Guid? AddedUserId { get; set; } = Guid.Empty;
        public string? AddedUserName { get; set; } = string.Empty;
        public DateTime? DateCreation { get; set; }
        public Guid? GoodsId { get; set; } = Guid.Empty;
        public string? GoodsName { get; set; } = string.Empty;
        public double Netto { get; set; } = 0;
        public bool IsManualInput { get; set; } = false;
        public bool IsRemoved { get; set; } = false;
    }
}
