// <auto-generated />
namespace ASW.Shared.Requests.RemoteCamera
{
    public class AddRemoteCameraRequest
    {
        public Guid Id { get; set; }
        public Guid PostId { get; set; } = Guid.Empty;
        public string Name { get; set; } = string.Empty;
        public string URL { get; set; } = string.Empty;
        public int SequenceNumber { get; set; }
        public bool IsRecognize { get; set; } = false;
        public double X { get; set; } = 0;
        public double Y { get; set; } = 0;
        public double Z { get; set; } = 0;
        public bool IsRemoved { get; set; } = false;
    }
}
