// <auto-generated />
namespace ASW.Shared.Requests.RemoteAxesDist
{
    public class AddRemoteAxesDistRequest
    {
        public Guid Id { get; set; }
        public Guid WeighingId { get; set; } = Guid.Empty;
        public int Number { get; set; }
        public double Tara { get; set; } = 0;
        public double Brutto { get; set; } = 0;
        public bool IsRemove { get; set; } = false;
    }
}
