// <auto-generated />
namespace ASW.Shared.Requests.RemoteWeighing
{
    public class AddRemoteWeighingRequest
    {
        public Guid Id { get; set; }
        public int Number { get; set; }
        public Guid PostId { get; set; } = Guid.Empty;
        public Guid? AddedUserId { get; set; } = Guid.Empty;
        public string? AddedUserName { get; set; } = string.Empty;
        public DateTime? DateCreation { get; set; }
        public DateTime? DateTara { get; set; }
        public DateTime? DateBrutto { get; set; }
        public DateTime? DateRegistration { get; set; }
        public double? Tara { get; set; } = 0;
        public double? Brutto { get; set; } = 0;
        public double? Netto { get; set; } = 0;
        public Guid? CarId { get; set; } = Guid.Empty;
        public string? CarName { get; set; } = string.Empty;
        public Guid? DriverId { get; set; } = Guid.Empty;
        public string? DriverName { get; set; } = string.Empty;
        public Guid? GoodsId { get; set; } = Guid.Empty;
        public string? GoodsName { get; set; } = string.Empty;
        public Guid? TrailerId { get; set; } = Guid.Empty;
        public string? TrailerName { get; set; } = string.Empty;
        public Guid? SenderId { get; set; } = Guid.Empty;
        public string? SenderName { get; set; } = string.Empty;
        public Guid? RecipientId { get; set; } = Guid.Empty;
        public string? RecipientName { get; set; } = string.Empty;
        public Guid? CarrierId { get; set; } = Guid.Empty;
        public string? CarrierName { get; set; } = string.Empty;
        public Guid? PayerId { get; set; } = Guid.Empty;
        public string? PayerName { get; set; } = string.Empty;
        public string? RFID { get; set; } = string.Empty;
        public string? DeliveryMethod { get; set; } = string.Empty;
        public bool IsFormed { get; set; } = false;
        public bool IsEmptyWeighing { get; set; } = false;
        public bool IsBloc { get; set; } = false;
        public bool IsRemoved { get; set; } = false;
    }
}
