// <auto-generated />
using ASW.RemoteViewing.Infrastructure.Data.Base;
using System.ComponentModel.DataAnnotations;

namespace ASW.RemoteViewing.Features.RemoteCamera.Entities
{
    public class RemoteCameraEF : IEntity<Guid>, ISoftRemovable, IHasPlaceMetadata
    {
        [Key]
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid PlaceId { get; set; }
        public string PlaceName { get; set; } = string.Empty;
        public Guid CameraId { get; set; }
        public Guid PostId { get; set; } = Guid.Empty;
        public string Name { get; set; } = string.Empty;
        public string URL { get; set; } = string.Empty;
        public int SequenceNumber { get; set; }
        public bool IsRecognize { get; set; }
        public double X { get; set; } = 0;
        public double Y { get; set; } = 0;
        public double Z { get; set; } = 0;
        public bool IsRemoved { get; set; }
    }
}
