// <auto-generated />
namespace ASW.Shared.Requests.RemoteEmptyWeighing
{
    public class AddRemoteEmptyWeighingRequest
    {
        public Guid Id { get; set; }
        public Guid PostId { get; set; } = Guid.Empty;
        public string? PostName { get; set; } = string.Empty;
        public string? CarName { get; set; } = string.Empty;
        public string? TrailerName { get; set; } = string.Empty;
        public DateTime? Date { get; set; }
        public double Weight { get; set; } = 0;
        public bool Stability { get; set; } = false;
        public bool IsRemoved { get; set; } = false;
    }
}
