// <auto-generated />
namespace ASW.Shared.Requests.RemoteEmptyWeighingPhoto
{
    public class AddRemoteEmptyWeighingPhotoRequest
    {
        public Guid Id { get; set; }
        public Guid EmptyWeighingId { get; set; } = Guid.Empty;
        public DateTime? Date { get; set; }
        public string Base64Image { get; set; } = string.Empty;
        public bool IsRemove { get; set; } = false;
    }
}
